const style = document.createElement('style');
style.textContent = `.promise-grid article{position:relative;overflow:hidden;border-radius:6px;background:#fff;padding:25px 18px 18px;box-shadow:0 8px 24px #0a254012}.promise-grid article:after{content:'✓';position:absolute;right:18px;top:18px;width:30px;height:30px;border-radius:50%;display:grid;place-items:center;background:#f3d89f;color:#0a2540;font-weight:800}.promise-grid article:nth-child(2):after{background:#dce9f5;color:#1e5fa8}.promise-grid article:nth-child(3):after{background:#d8e9df;color:#247451}.icon{display:grid;place-items:center;width:44px;height:44px;border-radius:50%;font-size:1.65rem;color:#0a2540;background:#f3d89f;margin-bottom:20px;font-weight:700}.promise-grid article:nth-child(2) .icon{background:#dce9f5;color:#1e5fa8}.promise-grid article:nth-child(3) .icon{background:#d8e9df;color:#247451}.promise-grid article:before{content:'';display:block;height:120px;margin:-25px -18px 20px;background-size:cover;background-position:center;opacity:.95}.promise-grid article:nth-child(1):before{background-image:linear-gradient(0deg,#0a2540aa,#0a254000),url('context-diagnostico.png')}.promise-grid article:nth-child(2):before{background-image:linear-gradient(0deg,#0a2540aa,#0a254000),url('context-equipe.png')}.promise-grid article:nth-child(3):before{background-image:linear-gradient(0deg,#0a2540aa,#0a254000),url('hero-marcelo.png')}.testimonials blockquote{position:relative}.testimonials blockquote:before{content:'“';position:absolute;right:20px;top:4px;font:800 3.5rem Manrope;color:#dbe6f0}.steps article{position:relative}.steps article:before{content:'✓';display:grid;place-items:center;width:28px;height:28px;border-radius:50%;background:#f3d89f;color:#0a2540;font-weight:800;position:absolute;left:-14px;top:0}.context-image-note{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin:0 0 38px}.context-image-note figure{margin:0;position:relative;overflow:hidden;border-radius:6px;background:#0a2540}.context-image-note img{display:block;width:100%;height:190px;object-fit:cover}.context-image-note figcaption{position:absolute;bottom:0;left:0;right:0;padding:30px 14px 12px;color:#fff;font-size:.78rem;font-weight:700;background:linear-gradient(transparent,#0a2540)}@media(max-width:800px){.context-image-note{grid-template-columns:1fr}.promise-grid article:before{height:150px}}`;
document.head.appendChild(style);
const heading = document.querySelector('.promise h2');
if (heading) { const note = document.createElement('div'); note.className = 'context-image-note'; note.innerHTML = '<figure><img src="context-diagnostico.png" alt="Dono de indústria analisando resultados com um consultor" loading="lazy"><figcaption>Decisão baseada no que acontece no seu negócio.</figcaption></figure><figure><img src="context-equipe.png" alt="Equipe comercial alinhando metas em uma empresa tradicional" loading="lazy"><figcaption>Time alinhado para executar o próximo passo.</figcaption></figure>'; heading.after(note); }
document.querySelector('#lead-form').addEventListener('submit', function (event) {
  event.preventDefault();
  const status = this.querySelector('.form-status');
  status.textContent = 'Recebi seus dados. Em breve, você receberá o link para escolher o melhor horário.';
  this.reset();
});
